### ISSUE TITLE
[Request] Need a HelloWorld demo

### ISSUE THREAD

**Issue by dzunglht** [react-native-community/boost-for-react-native#2]
Hi folks,
Would you please provide us a simple helloworld demo on RN ?
Many thanks

**Comment by satya164** [comment]
This is not the React Native repo. Also you can get a hello world demo with `react-native init` or here - https://snack.expo.io

**Comment by meow0703** [comment]
@satya164 execute me ? do you understand my question ? i asked for a demo RN making use of this boost library. Please dont close ticket if you don't understand what the purpose it is !
Regards
