### ISSUE TITLE
Error installing boost

### ISSUE THREAD

**Issue by maniveltvl** [react-native-community/boost-for-react-native#22]
Hi, Team

I am getting the below error while running the react native app with nx. Whenever it is running pod install I am getting the below error 

`Installing RecaptchaInterop (100.0.0)
Installing Rokt-Widget (4.2.0)
Installing SSZipArchive (2.5.5)
Installing SocketRocket (0.6.1)
Installing Stripe (19.4.1)
Installing Yoga (1.14.0)
Installing boost (1.76.0)

[!] Error installing boost
[!] /usr/bin/curl -f -L -o /var/folders/gz/5srqx9kj75320shgkdvmfd540000gp/T/d20240617-96589-5gtt6/file.tbz https://archives.boost.io/release/1.83.0/source/boost_1_83_0.tar.bz2 --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.15.2 cocoapods-downloader/2.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 **99  117M   99  116M    0     0  8243k      0  0:00:14  0:00:14 --:--:--     0**
**curl: (18) transfer closed with 929491 bytes remaining to read**

[!] NPM package '@react-native-firebase/remote-config' depends on '@react-native-firebase/app' v19.2.2 but found v19.0.1, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/remote-config' depends on '@react-native-firebase/app' v19.2.2 but found v19.0.1, this might cause build issues or runtime crashes.

Running pod install failed, see above.
Do you have CocoaPods (https://cocoapods.org/) installed?

Check that your XCode path is correct:
sudo xcode-select --print-path

If the path is wrong, switch the path: (your path may be different)
sudo xcode-select --switch /Applications/Xcode.app

 >  NX   Command failed: pod install  

Error: Command failed: pod install  
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:889:11)
    at execSync (node:child_process:961:15)
    at podInstall (/Users/.../node_modules/@nx/react-native/src/utils/pod-install-task.js:63:38)
    at /Users/.../node_modules/@nx/react-native/src/utils/pod-install-task.js:41:16
    at podInstall (/Users/.../node_modules/@nx/react-native/src/executors/pod-install/pod-install.impl.js:8:77)
    at podInstall.next (<anonymous>)
    at getLastValueFromAsyncIterableIterator (/Users/.../node_modules/nx/src/utils/async-iterator.js:13:27)
    at iteratorToProcessStatusCode (/Users/.../node_modules/nx/src/command-line/run/run.js:41:94)

 ———————————————————————————————————————————————————————`

**Boost.podspec**

`# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

Pod::Spec.new do |spec|
  spec.name = 'boost'
  spec.version = '1.76.0'
  spec.license = { :type => 'Boost Software License', :file => "LICENSE_1_0.txt" }
  spec.homepage = 'http://www.boost.org'
  spec.summary = 'Boost provides free peer-reviewed portable C++ source libraries.'
  spec.authors = 'Rene Rivera'
  spec.source = { :http => 'https://archives.boost.io/release/1.83.0/source/boost_1_83_0.tar.bz2',
                   :sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }

  # Pinning to the same version as React.podspec.
  spec.platforms = { :ios => '11.0' }
  spec.requires_arc = false

  spec.module_name = 'boost'
  spec.header_dir = 'boost'
  spec.preserve_path = 'boost'
end
`

npm react-native -v : 10.5.0
node -v : v22.2.0

**Comment by cortinico** [comment]
This is not the issue tracker for react-native, please report them here:
https://github.com/facebook/react-native/issues
