### ISSUE TITLE
Cocoapods compatibility

### ISSUE THREAD

**Issue by itchingpixels** [react-native-community/boost-for-react-native#3]
There's an issue on react-native I've opened: https://github.com/facebook/react-native/issues/16381
I'm trying to use this version of boost instead of what's currently referred to as 'boost' in Folly.podspec, since the release version that can be downloaded from here is 4-5x smaller.

This is the podspec I've added
https://github.com/languagedrops/react-native/commit/1c3f1ab55aa8541bde2adbc4c4f25914a5731021

which should be the same as:
https://github.com/CocoaPods/Specs/blob/master/Specs/9/9/d/boost/1.59.0/boost.podspec.json

except the download URL.

But when I try to run the project with boost installed from this repo, I get the following error:
![image](https://user-images.githubusercontent.com/5416288/31590319-f5029248-b205-11e7-9903-cb8822ac1230.png)

Are there any plans of making a pod out of this?

Thank you!

**Comment by bestander** [comment]
@itchingpixels, thanks for digging the details.
Are you up to send a PR to fix that?

**Comment by itchingpixels** [comment]
I'd be happy to do that, but haven't got around making it work just yet - I don't know what the delta is between this and the 1.59.0 release that's on cocoapods, but it's really confusing!

**Comment by itchingpixels** [comment]
it seems like there's some magic (at least to me) going on with preserve_paths that I don't understand (why is it needed at all?) in the original podspec. will try a few different things and report back.

**Comment by bestander** [comment]
@ide, do you have some context on this to help us out?

**Comment by ide** [comment]
I don't have a lot of context around this and @mhorowitz set up the third-party pods. If we go in this direction I think we should just add a podspec to this repo to install direct from GitHub but not publish to CocoaPods since we're not going to remember to keep it updated.

**Comment by bestander** [comment]
Pinged @mhorowitz, thanks @ide

**Comment by mhorowitz** [comment]
When I set up CocoaPods for CxxBridge, boost worked out of the box for me.  I never even looked at the original Podspec, so I don't know why it's set up the way it is.

My best guess why it isn't working now is that something in the maze of ifdefs changed, and now `type_index.h` is being included, but the `type_index/` directory isn't included in any of the subspecs in the podspec you linked.  Adding it to one of the existing subspecs, or making a new one, would be the next thing to try.

**Comment by fishmwei** [comment]
@mhorowitz  
I add a subspec to boost.podspec , then pod install again , it works.

```
#added by hmw
spec.subspec 'type_index-includes' do |cs|
    cs.preserve_paths = 'boost/type_index/**/*.hpp'
 end
```

**Comment by itchingpixels** [comment]
Great!!! Sorry guys that I backed out, had been super busy with a release...
@fishmwei : do you have a PR?

**Comment by fishmwei** [comment]
@itchingpixels  I have a PR in your branch  [PR](https://github.com/languagedrops/react-native/pull/1)

**Comment by bestander** [comment]
Anyone wants to send a PR for this repo?
I suppose other people will have a similar problem.

Thanks @fishmwei for finding the solution.

**Comment by itchingpixels** [comment]
I've created a PR: https://github.com/facebook/react-native/pull/16756
This is my first PR to react-native, I'm not sure what to do to get it merged in - if you can bump it, that may work?

**Comment by bestander** [comment]
Thanks, I'll ping iOS people internally

**Comment by itchingpixels** [comment]
@bestander do you have any news regarding this? I'm not sure whom should I be in contact with.

**Comment by Pranit-Harekar** [comment]
+1 any update ?

**Comment by bestander** [comment]
Trunk is still broken, I'll merge it once it is green: https://circleci.com/gh/facebook/react-native/tree/master. 
Someone from RN team is on it but a PR with a fix is welcome.
