### ISSUE TITLE
Is this used for iOS build?

### ISSUE THREAD

**Issue by sesm** [react-native-community/boost-for-react-native#8]
# Question

README now says `This is a copy of Boost that is used to build React Native (Android) from source`, but I've encountered [this error](https://stackoverflow.com/questions/56614768/how-to-fix-boost-operators-hpp-file-not-found-error-in-react-native) , which suggest that boost is also used for iOS build.
Should README be updated to reflect this?

**Comment by sesm** [comment]
Created a PR to fix README https://github.com/react-native-community/boost-for-react-native/pull/9

**Comment by fabriziobertoglio1987** [comment]
the errors for me was 

>`ios/Pods/boost-for-react-native/boost/operators.hpp:97:10: 'boost/config.hpp' file not found` 

and this solution worked for me [here](https://stackoverflow.com/a/59287904/7295772)
